### ISSUE TITLE
An error occurred (UnrecognizedClientException) when calling the GetAuthorizationToken operation: The security token included in the request is invalid. Error: Cannot perform an interactive login from a non TTY device 

### ISSUE THREAD

**Issue by Bash-mocart** [CircleCI-Public/aws-ecr-orb#163]
### Orb version
circleci/aws-ecr@7.2.0

### What happened

Log into Amazon ECR in the workflow aws-ecr/build-and-push-image isnt passing

### Expected behavior
Should be able to run without any trouble

**Comment by yaningo** [comment]
Hi, @Bash-mocart, were you using the default executor for the `aws-ecr/build-and-push-image` job?

If you don't specify an `executor` (https://circleci.com/developer/orbs/orb/circleci/aws-ecr#jobs-build-and-push-image), it'll use the [default one](https://circleci.com/developer/orbs/orb/circleci/aws-ecr#executors-default) which has AWS CLI `v2.0.52` installed.

As per the [AWS CLI command reference](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecr/get-login-password.html) `get-login-password` is supported using the latest version of AWS CLI version 2 or in v1.17.10 or later of AWS CLI version 1, but it's not clear which exact version 2 started supporting it.

**Comment by yuichiro12** [comment]
Hi.
I tried with non-default executor and I found it still happens in circleci/aws-ecr@>=v7.0.0.

The workaround is using `override-installed` in aws-cli orb:

```yaml
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.0
  aws-ecr: circleci/aws-ecr@7.0.0
executors:
  docker_build:
    machine:
      docker_layer_caching: true
...
jobs:
  build-and-push-image:
    executor: docker_build
    steps:
      - checkout
      - aws-cli/setup:
          override-installed: true
      - aws-ecr/build-and-push-image:
      ...
```

`get-login-password` is added in aws-cli v2.0.0, so any awscli v2 will do.
FYI: 
https://github.com/aws/aws-cli/blob/v2/CHANGELOG.rst#200

**Comment by maximgtoy** [comment]
I played around and found out it was the --profile flag that fails the command, while running aws ecr get-login-password --region $AWS_DEFAULT_REGION in a ssh session in the same container worked completely fine.

**Comment by callumcieciala** [comment]
I am encountering this issue on an initial setup of a CircleCI pipeline, is this planned to be fixed or is there a workaround? Does this mean the orb is not usable with the examples it gives?

**Comment by callumcieciala** [comment]
@brivu 
Hey Brian,

I believe I am trying to log in without a profile. Currently I have hand written the steps in my pipeline to interact with my ECR repo and I am not using a profile and everything is working fine. 
When using the orb with the settings / defaults in the examples I was getting the interactive login error message.

Thanks for reaching out and looking at this. 

Kind regards,
Cal

**Comment by brivu** [comment]
Hey Cal!  

Thanks for letting me know.  I'm adding in validation for the profile so that if it doesn't exist, the `--profile` flag does not get added to the `ecr login` command.  

I'm aiming to have this fix in by this week or early next! 

Best, 
Brian

**Comment by brivu** [comment]
Hey Cal! 

This issue has been addressed and merged in this PR: https://github.com/CircleCI-Public/aws-ecr-orb/pull/172

Cheers! 
Brian

**Comment by greenreign** [comment]
This is still an issue in 8.2.1

**Comment by fabiomilheiro** [comment]
Still an issue here. Can anyone help narrow down the issue please?

**Comment by iulianbarbu** [comment]
I am using `circleci/aws-ecr@8.1.2`. I have a similar problem when using `aws-ecr/ecr-login` command.
