### ISSUE TITLE
Multiple tags per image

### ISSUE THREAD

**Issue by Vlaaaaaaad** [CircleCI-Public/aws-ecr-orb#20]
### Orb version

3.0.0

### What happened

Currently images can only have 1 tag as per your example due to [how the job is written](https://github.com/CircleCI-Public/aws-ecr-orb/blob/3e435388beb8a9abdc2c2369fbf8b6ac44cff8ab/src/commands/build-image.yml#L44):
```
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0

workflows:
  complete_build_and_push:
    jobs:
      - aws-ecr/build_and_push_image:
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          region: AWS_REGION_ENV_VAR_NAME
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          repo: myECRRepository
          # ECR image tag, defaults to "latest"
          tag: ${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}
```

### Expected behavior

There is a desire for an image to have multiple tags, in our case both the `${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}`, the `${CIRCLE_SHA1}`, and say `latest`.

```
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0

workflows:
  complete_build_and_push:
    jobs:
      - aws-ecr/build_and_push_image:
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          region: AWS_REGION_ENV_VAR_NAME
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          repo: myECRRepository
          tag: [ ${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}, ${CIRCLE_SHA1}, "latest"]
```

This is currently blocked by https://ideas.circleci.com/ideas/CCI-I-701 which asks for list parameters to be enabled.

Are there any workaround for this?

**Comment by kgriffiths** [comment]
This would be great to have

**Comment by iynere** [comment]
yeah we can definitly make this happen even without a `list`-type parameter. it would have to be a comma-separated string, which would then be parsed out in the orb source code

**Comment by iynere** [comment]
i see there are a lot of upvotes on this issue—does anyone wanna take a crack at a PR ?

here's some examples of how we usually do this:

https://github.com/CircleCI-Public/slack-orb/blob/staging/src/commands/notify.yml#L92-L101
https://github.com/CircleCI-Public/gcp-binary-authorization-orb/blob/master/src/commands/configure-policy.yml#L151-L181

if not, we will get to it eventually, but it will have to get slotted behind a few other things

**Comment by lokst** [comment]
Resolved in version`circleci/aws-ecr@6.3.0` (See: https://github.com/CircleCI-Public/aws-ecr-orb/pull/45)

**Comment by danielmarzini** [comment]
It seems that this issue is still valid, here's my configuration with the 6.3.0 version:

aws-ecr/build-and-push-image:
          requires:
            - production-build
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          region: AWS_REGION_ENV_VAR_NAME
          tag: 'latest,${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}'
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          create-repo: true
          dockerfile: Dockerfile
          repo: *********
          attach-workspace: true

and here's the error:
```
docker build \
   \
  -f Dockerfile \
  -t $AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME/*******:latest,${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM} \
  .
invalid argument "**********.dkr.ecr.eu-central-1.amazonaws.com/******:latest,kubernetes-docker-integration-113" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
Exited with code 125
```
