### ISSUE TITLE
Producing zero-size image on machine image ubuntu-2204:current

### ISSUE THREAD

**Issue by vatima2016** [CircleCI-Public/aws-ecr-orb#300]
### Orb version
9.0.0
machine image: ubuntu-2204:current

### What happened
After updating from 8.2.1 to 9.0.0 there are generated one image index,  one zero-size image and one non-zero-size image.
![aws-ecr-orb 2023-08-24 a las 10 45 56](https://github.com/CircleCI-Public/aws-ecr-orb/assets/17909224/04679afd-010f-496f-976e-cf2cbd22cac6)

Old usage:
```
# 8.2.1 - image tag 0.6.3-8433
- aws-cli/setup:
    role_arn: <<parameters.role_arn>>
- aws-ecr/build-and-push-image:
    repo: <<parameters.repo>>
    create-repo: false
    platform: <<parameters.platform>>
    skip-when-tags-exist: false
    dockerfile: <<parameters.dockerfile>>
    tag: <<parameters.tag>>
    no-output-timeout: 20m
    checkout: false
    attach-workspace: false
    workspace-root: ~/project
    registry-id: AWS_ACCOUNT_ID
```
New usage:
```
# 9.0.0  - image tag 0.6.3-8466
- aws-ecr/build_and_push_image:
    repo: <<parameters.repo>>
    create_repo: false
    platform: <<parameters.platform>>
    auth:
      - aws-cli/setup:
          role_arn: <<parameters.role_arn>>
    skip_when_tags_exist: false
    dockerfile: <<parameters.dockerfile>>
    tag: <<parameters.tag>>
    no_output_timeout: 20m
    checkout: false
    attach_workspace: false
    workspace_root: ~/project
```
Where:
```
platform: linux/arm64
machine:
    image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: arm.medium
```

### Expected behavior
As far as the image should be generated for the only platform I'd expect either the old behaviour producing the only image without any index or at least one index and one non-zero-size image.

### Workaround
Pin machine image version to ubuntu-2204:2022.07.1

**Comment by fwhenin** [comment]
i'm having the same problem

**Comment by Renkas** [comment]
same here ...

**Comment by AustinAMeyer** [comment]
I am having this same issue. It didn't show up until I switched to using Docker executor with cimg/deploy:2023.09.1. I was using the machine executor with ubuntu-2204:2022.07.1 and it would just build 1 image. It would be great if we could get his fixed up since I am making the move to ARM docker images now that they are available.

**Comment by itsyuvalcohen** [comment]
I'm experiencing the same problem, fixed after changing the executor to ubuntu-2204:2022.07.1

**Comment by brivu** [comment]
Hey everyone! 

This was an image issue and has been fixed. I just tested this out on ` ubuntu-2204:current` and compared the manifest to  `ubuntu-2204:2022.07.1` and they both don't have a zero sized image.

I'll close this out for now but please feel free to reopen if you all are still running into this issue.

Thanks again, 
Brian

**Comment by brivu** [comment]
Hey everyone, 

The seems to be an issue with docker and the latest version of the `ubuntu` that's causing this. To prevent this from happening, you can add the `--provenance=false` to the `extra_build_args` parameter. 

Reference here #325 and [here](https://github.com/docker/buildx/issues/1509)

-Brian

**Comment by CharlesBuss** [comment]
The issue still happening on orb version 9.4.0 and `ubuntu-2204:current`.
Adding the --provenance=false solved the issue.
